name: polymer_elements
version: 0.0.13
authors: 
- Erik Grimes <erik.grimes@gmail.com>
- Günter Zöchbauer <guenter@gzoechbauer.com>
description: >
  A Dart port of polymer-elements 
  (https://github.com/Polymer/polymer-elements).
homepage: https://github.com/ErikGrimes/polymer_elements
documentation: http://erikgrimes.github.io/polymer_elements/docs/index.html
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  polymer: ">=0.9.0 < 0.10.0"
  polymer_ui_elements: 0.0.12
dev_dependencies:
  unittest: any
